/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObligationsRouteImport } from './routes/Obligations'
import { Route as LegalActsRouteImport } from './routes/Legal-acts'
import { Route as IndexRouteImport } from './routes/Index'
import { Route as AboutRouteImport } from './routes/About'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'

const ObligationsRoute = ObligationsRouteImport.update({
  id: '/Obligations',
  path: '/Obligations',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalActsRoute = LegalActsRouteImport.update({
  id: '/Legal-acts',
  path: '/Legal-acts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/Index',
  path: '/Index',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/About': typeof AboutRoute
  '/Index': typeof IndexRoute
  '/Legal-acts': typeof LegalActsRoute
  '/Obligations': typeof ObligationsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesByTo {
  '/About': typeof AboutRoute
  '/Index': typeof IndexRoute
  '/Legal-acts': typeof LegalActsRoute
  '/Obligations': typeof ObligationsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/About': typeof AboutRoute
  '/Index': typeof IndexRoute
  '/Legal-acts': typeof LegalActsRoute
  '/Obligations': typeof ObligationsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/About'
    | '/Index'
    | '/Legal-acts'
    | '/Obligations'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/About'
    | '/Index'
    | '/Legal-acts'
    | '/Obligations'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/About'
    | '/Index'
    | '/Legal-acts'
    | '/Obligations'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  IndexRoute: typeof IndexRoute
  LegalActsRoute: typeof LegalActsRoute
  ObligationsRoute: typeof ObligationsRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Obligations': {
      id: '/Obligations'
      path: '/Obligations'
      fullPath: '/Obligations'
      preLoaderRoute: typeof ObligationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Legal-acts': {
      id: '/Legal-acts'
      path: '/Legal-acts'
      fullPath: '/Legal-acts'
      preLoaderRoute: typeof LegalActsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Index': {
      id: '/Index'
      path: '/Index'
      fullPath: '/Index'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  IndexRoute: IndexRoute,
  LegalActsRoute: LegalActsRoute,
  ObligationsRoute: ObligationsRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
