/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObligationsRouteImport } from './routes/Obligations'
import { Route as LegalActsRouteImport } from './routes/Legal-acts'
import { Route as AboutRouteImport } from './routes/About'
import { Route as IndexRouteImport } from './routes/index'

const ObligationsRoute = ObligationsRouteImport.update({
  id: '/Obligations',
  path: '/Obligations',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalActsRoute = LegalActsRouteImport.update({
  id: '/Legal-acts',
  path: '/Legal-acts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Legal-acts': typeof LegalActsRoute
  '/Obligations': typeof ObligationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Legal-acts': typeof LegalActsRoute
  '/Obligations': typeof ObligationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/About': typeof AboutRoute
  '/Legal-acts': typeof LegalActsRoute
  '/Obligations': typeof ObligationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/About' | '/Legal-acts' | '/Obligations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/About' | '/Legal-acts' | '/Obligations'
  id: '__root__' | '/' | '/About' | '/Legal-acts' | '/Obligations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LegalActsRoute: typeof LegalActsRoute
  ObligationsRoute: typeof ObligationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Obligations': {
      id: '/Obligations'
      path: '/Obligations'
      fullPath: '/Obligations'
      preLoaderRoute: typeof ObligationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Legal-acts': {
      id: '/Legal-acts'
      path: '/Legal-acts'
      fullPath: '/Legal-acts'
      preLoaderRoute: typeof LegalActsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LegalActsRoute: LegalActsRoute,
  ObligationsRoute: ObligationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
